from LinkedList import LinkedList

linked_list = LinkedList()
# print(linked_list.to_array())
linked_list.add_last(12)
# print(linked_list.to_array())
linked_list.add_last(13)
# print(linked_list.to_array())
linked_list.add_last(14)
# print(linked_list.to_array())
linked_list.add_last(15)
# print(linked_list.to_array())
linked_list.add_last(16)
# print(linked_list.to_array())

# print(linked_list.to_array())
# linked_list.reverse()
# print(linked_list.to_array())
# print(linked_list.first)
# print(linked_list.last)
print(linked_list.kth_from_end(2))